name: Release

on:
  push:
    tags:
      - '*.*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Print version info
        id: semver
        run: |
          make version

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          cache-image: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        env:
          APPSCODE_ENV: prod
        run: |
          make release

      - uses: actions/upload-artifact@master
        with:
          name: bpf-opa-demo-binaries
          path: bin
